# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoOpenchargemap < Formula
  desc "Golang interface to OpenChargeMap with a 'chargemeup' CLI tool"
  homepage "https://github.com/neomantra/go-openchargemap"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.2.0/go-openchargemap_0.2.0_darwin_arm64.tar.gz"
      sha256 "570c78a673620491aa5685282f2e58bb61995e444e642fe628f39e16873f756f"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.2.0/go-openchargemap_0.2.0_darwin_amd64.tar.gz"
      sha256 "2fc13ffadc0a5d78b12fcf711044376c52d77585ae735757e326b7effc7e8dc9"

      def install
        bin.install "chargemeup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.2.0/go-openchargemap_0.2.0_linux_arm64.tar.gz"
      sha256 "40013c2488b83a77dd167d3056b517da7ffe17a3354ac7e129daf031199d4c0f"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.2.0/go-openchargemap_0.2.0_linux_amd64.tar.gz"
      sha256 "7b91035af9b17f456849e4230653e398268539a0c7b1982ccd9c98f07eed4b0e"

      def install
        bin.install "chargemeup"
      end
    end
  end
end
