# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoOpenchargemap < Formula
  desc "Golang interface to OpenChargeMap with a 'chargemeup' CLI tool"
  homepage "https://github.com/neomantra/go-openchargemap"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.3.0/go-openchargemap_0.3.0_darwin_amd64.tar.gz"
      sha256 "de7d82485f06ba879a337d5dc30bfd50dbf075b4f37be666db6a3ff452c6a3fe"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.3.0/go-openchargemap_0.3.0_darwin_arm64.tar.gz"
      sha256 "a73d7bb3e71430f82a0f195c975a2c21914e51a38bf9d2b5dbc6aa89c4dd9ea2"

      def install
        bin.install "chargemeup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.3.0/go-openchargemap_0.3.0_linux_arm64.tar.gz"
      sha256 "d344d6b51292fa4ec63c1cb7db117328dd25b46c5976cbe7b37bf468446dc698"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.3.0/go-openchargemap_0.3.0_linux_amd64.tar.gz"
      sha256 "0dde72fc0799d65e68b257e959cc4ffd7eccc9b38c2b1c7878b12d6851628b08"

      def install
        bin.install "chargemeup"
      end
    end
  end
end
