# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoOpenchargemap < Formula
  desc "Golang interface to OpenChargeMap with a 'chargemeup' CLI tool"
  homepage "https://github.com/neomantra/go-openchargemap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.1.0/go-openchargemap_0.1.0_darwin_arm64.tar.gz"
      sha256 "7d9225388995ab990749ee4368260b049a1c72c8c60cf8f6cb07fd566e977ff0"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.1.0/go-openchargemap_0.1.0_darwin_amd64.tar.gz"
      sha256 "415109a6053c617607d62c8f9f4412fbb3448cf179eae2fac4e0b877619ae25c"

      def install
        bin.install "chargemeup"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.1.0/go-openchargemap_0.1.0_linux_amd64.tar.gz"
      sha256 "43b1efbe4036c1e28544a961ab082f9ca6c74f64ef1ed8afb255d1547da51639"

      def install
        bin.install "chargemeup"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/go-openchargemap/releases/download/v0.1.0/go-openchargemap_0.1.0_linux_arm64.tar.gz"
      sha256 "b660ea3e62ca1f4f8b27080b4b5e353dd5a18de40d169bd840c83176862ee8c2"

      def install
        bin.install "chargemeup"
      end
    end
  end
end
