# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotf < Formula
  desc "Golang-based Time Formatter"
  homepage "https://github.com/neomantra/gotf"
  version "0.0.2"

  on_macos do
    url "https://github.com/neomantra/gotf/releases/download/v0.0.2/gotf_0.0.2_Darwin_all.tar.gz"
    sha256 "dabc8a6fbd342cf5e0cfc29eb3ec9000e4f75b70ce820d002a47bb5249ca0fe7"

    def install
      bin.install "gotf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/gotf/releases/download/v0.0.2/gotf_0.0.2_Linux_x86_64.tar.gz"
      sha256 "32e441d75ca79a6dc64bc4d67dc1168a49fafa30d0e402718d034f22cfad4577"

      def install
        bin.install "gotf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/gotf/releases/download/v0.0.2/gotf_0.0.2_Linux_arm64.tar.gz"
      sha256 "cce4b7eb42f296a315e24f2d472e0f293948610b835f216b3282348611490923"

      def install
        bin.install "gotf"
      end
    end
  end
end
