# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempted < Formula
  desc "Temporal TUI"
  homepage "https://github.com/neomantra/tempted"
  version "0.0.420"

  on_macos do
    url "https://github.com/neomantra/tempted/releases/download/v0.0.420/tempted_0.0.420_Darwin_all.tar.gz"
    sha256 "e83837cba1cb2c328289c87a2a334116829c39750b6e7735704482b55e3aff17"

    def install
      bin.install "tempted"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/tempted/releases/download/v0.0.420/tempted_0.0.420_Linux_arm64.tar.gz"
      sha256 "6001b51e3d805a3eec0086088256468b25756b6c283177adf10b8d7ea19d93a1"

      def install
        bin.install "tempted"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/tempted/releases/download/v0.0.420/tempted_0.0.420_Linux_x86_64.tar.gz"
      sha256 "1a4f45aa36641e661fe6e301ffa43da2def9168c0814ef4f6d5f49f84a961073"

      def install
        bin.install "tempted"
      end
    end
  end
end
