# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Golang-based Time Formatter"
  homepage "https://github.com/neomantra/tf"
  version "0.0.3"

  on_macos do
    url "https://github.com/neomantra/tf/releases/download/v0.0.3/tf_0.0.3_Darwin_all.tar.gz"
    sha256 "52bd2981beb94ba3137f7111e02485ed8177bb7c1a91f07372701ff50f9ee840"

    def install
      bin.install "tf"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/tf/releases/download/v0.0.3/tf_0.0.3_Linux_arm64.tar.gz"
      sha256 "c4d9d9a4d46fb67675beca02b1a27c654af35e6596beb747519f55d49a77a4be"

      def install
        bin.install "tf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/tf/releases/download/v0.0.3/tf_0.0.3_Linux_x86_64.tar.gz"
      sha256 "308ed657422deea302791b303e7ad77cbc29df5d5c064425bb0ad5d23e51e438"

      def install
        bin.install "tf"
      end
    end
  end
end
