# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tf < Formula
  desc "Golang-based Time Formatter"
  homepage "https://github.com/neomantra/tf"
  version "0.0.4"

  on_macos do
    url "https://github.com/neomantra/tf/releases/download/v0.0.4/tf_0.0.4_Darwin_all.tar.gz"
    sha256 "f598ac214c13013e7448e9a3bbc2ac89b5eff9712cf837ff395dcdcb3b5bfebd"

    def install
      bin.install "tf"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/tf/releases/download/v0.0.4/tf_0.0.4_Linux_arm64.tar.gz"
      sha256 "beee2368cf3c5b2f1640e1acbaa677657151058a730ad3574f4d3bc5b926569c"

      def install
        bin.install "tf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/tf/releases/download/v0.0.4/tf_0.0.4_Linux_x86_64.tar.gz"
      sha256 "993d5c82975e2a111e406837cf6f95f841b6f2975cd9e2c0a6e197bc79d429e0"

      def install
        bin.install "tf"
      end
    end
  end
end
