# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wander < Formula
  desc "a terminal app for Nomad by HashiCorp"
  homepage "https://github.com/neomantra/wander"
  version "0.0.1"

  on_macos do
    url "https://github.com/neomantra/wander/releases/download/v0.0.1/wander_0.0.1_Darwin_all.tar.gz"
    sha256 "e8272d1279e6ae60e9c18de753a80d0e151cf424b43a6f4545e3f17115dd71e7"

    def install
      bin.install "wander"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/neomantra/wander/releases/download/v0.0.1/wander_0.0.1_Linux_x86_64.tar.gz"
      sha256 "e6f5a5385d0ba7c6cc5b00127ce577a3a1f5eeea6e62dfde4561dd80bfbdd98c"

      def install
        bin.install "wander"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neomantra/wander/releases/download/v0.0.1/wander_0.0.1_Linux_arm64.tar.gz"
      sha256 "41216bd6f4ed133df272ea62cb6c5619246908134bc5200d2693a0dd499b1fd2"

      def install
        bin.install "wander"
      end
    end
  end
end
